### PR TITLE
Refresh converter to CLIP pages

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
- recognize placeholders with `(s)` like `{{/file_or_directory(s)}}`
- convert more special placeholders like `{{user(s)}}`
- recognize brace expansion in placeholders like `{{path/to/image_file{1,2}}}`
- convert singular option placeholders
- convert paired option placeholders like `{{--install|--remove}}` to `{option flag: --install, --remove}`

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]

**Comment by EmilySeville7cfg** [comment]
@kbdharun, can u play with this converter? Maybe u find some bugs or suggest enhancements. 😄

**Comment by kbdharun** [comment]
> @kbdharun, can u play with this converter? Maybe u find some bugs or suggest enhancements. 😄

Sure will try it later today.

**Comment by EmilySeville7cfg** [comment]
Hmmm... What converter is missing (if not implementing a proper parser, just use sed) - handling brace expansions. It means that `{{file{1,2,3}}` will not be converted at all to `{file* value}`.

**Comment by EmilySeville7cfg** [comment]
@kbdharun, @navarroaxel, feel free to merge PR when u check converter functionality. :)

**Comment by EmilySeville7cfg** [comment]
@kbdharun, @navarroaxel, feel free to merge PR when u check converter functionality. :)

**Comment by EmilySeville7cfg** [comment]
@kbdharun, @navarroaxel, feel free to merge PR when u check converter functionality. :)

**Pull request merged**
