### PR TITLE
Color theme support

### LINKED ISSUE #15: Create JSON schema for color schemas and add support for coloring from specific theme files
Possible syntax: `clip-view --theme <path/to/scheme.clipt <command>`.

`.clipt` extension stands for `Command Line Interface Page Theme`

### PR DESCRIPTION
**Pull request by EmilySeville7cfg**
closes #15 

60 color settings available (use `bash ./clip-view.sh -h | grep '\$' | wc -l` to check):

image

## Notes

`-cc|--clear-cache` flag is replaced with `-cpc|--clear-page-cache`.

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
image

@blueglyph, here is how to use color themes. :)

**Comment by hyperupcall** [comment]
@EmilySeville7cfg SchemaStore has a requirement that schemas must have some minimal level of popularity - I don't think personal schemas as these meet that requirement?

**Comment by EmilySeville7cfg** [comment]
> @EmilySeville7cfg SchemaStore has a requirement that schemas must have some minimal level of popularity - I don't think personal schemas as these meet that requirement?

In other words, how many project stars should I have in your opinion?

**Comment by hyperupcall** [comment]
@EmilySeville7cfg My personal limit when adding schemas for other repositories is a thousand stars - there is always a risk of the project not working out and needing to remove the stale schema. If somebody else chooses to write the schema, then I guess the bar doesn't have to be as high - say a few hundred stars, but the point is that there are a more than a few dozen people benefiting from the schema and that each schema is from some community where people would at least recognize the project.

**Pull request merged**
